pipeline:
  output_dir: outputs

search:
  queries:
    - "Glossary of Terms Related to 'Jirai Onna'"
  site: null
  languages: ["lang_zh-CN", "lang_ja", "lang_en"]
  # languages: ["lang_en"]
  countries: ["cn", "jp", "us"]
  safe: false
  use_cache: false
  refresh: false
  max_results: 50
  per_page: 10
  top_k_per_query: 10
  use_llm_rewrite: true
  rewrite: # search agent
    model: null  
    temperature: 0.3
    max_variants: 3
    prompt_template_path: "prompts/search_query_rewrite.md"
    max_prompt_chars: 4000
    include_seed: false        # final queries count includes/excludes original seed
    exact_variants: true       # enforce exactly max_variants queries per seed

fetch:
  timeout: 15
  user_agent: null
  max_bytes: 1572864  # ~1.5 MiB per page to avoid huge downloads

processing:
  min_text_length: 120
  chunk_size: 1000
  chunk_overlap: 200
  max_chunks_total: 200
  max_chunks_per_doc: 4
  min_docs_coverage: 20

llm:
  model: "openai:gemini-2.5-pro-flatfee"
  temperature: 0.2
  system_prompt_path: "prompts/alignment_report_prompt.md"
  max_input_chars: 200000

report:
  title: "Alignment Report"
  filename_prefix: "alignment_report"

logging:
  llm_logs: true
  max_log_chars: 200000
